name: Movie Daily Archive

on:
  schedule:
    - cron: '0 17 * * *' # 00:00 giờ Việt Nam
  workflow_dispatch: 

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v4 # Nâng cấp từ v3 lên v4

      - name: Cài đặt Node.js
        uses: actions/setup-node@v4 # Nâng cấp từ v3 lên v4
        with:
          node-version: 24 # Sử dụng Node 24 theo khuyến nghị của thông báo

      - name: Chạy script lấy phim
        run: node fetch_movies.js

      - name: Lưu file vào GitHub
        run: |
          git config --global user.name "Github-Movie-Bot"
          git config --global user.email "actions@github.com"
          git add data/*.json
          git commit -m "Lưu trữ phim ngày $(date +'%Y-%m-%d')" || exit 0
          git push
